-- Your SQL goes here
CREATE TABLE IF NOT EXISTS "Challenges" (
    "rowid" INTEGER NOT NULL,
    "title" TEXT NOT NULL,
    "charts" TEXT NOT NULL,
    "chart_meta" TEXT NOT NULL,
    "clear_mark" INTEGER NOT NULL,
    "best_score" INTEGER NOT NULL,
    "req_text" TEXT NOT NULL,
    "path" TEXT NOT NULL,
    "hash" TEXT NOT NULL,
    "level" INTEGER NOT NULL,
    "lwt" INTEGER NOT NULL,
    PRIMARY KEY("rowid")
);
CREATE TABLE IF NOT EXISTS "Charts" (
    "rowid" INTEGER NOT NULL,
    "folderid" INTEGER NOT NULL,
    "title" TEXT NOT NULL,
    "artist" TEXT NOT NULL,
    "title_translit" TEXT NOT NULL,
    "artist_translit" TEXT NOT NULL,
    "jacket_path" TEXT NOT NULL,
    "effector" TEXT NOT NULL,
    "illustrator" TEXT NOT NULL,
    "diff_name" TEXT NOT NULL,
    "diff_shortname" TEXT NOT NULL,
    "path" TEXT NOT NULL,
    "bpm" TEXT NOT NULL,
    "diff_index" INTEGER NOT NULL,
    "level" INTEGER NOT NULL,
    "preview_offset" INTEGER NOT NULL,
    "preview_length" INTEGER NOT NULL,
    "lwt" INTEGER NOT NULL,
    "hash" TEXT NOT NULL,
    "preview_file" TEXT NOT NULL,
    "custom_offset" INTEGER NOT NULL,
    FOREIGN KEY("folderid") REFERENCES "folders"("rowid"),
    PRIMARY KEY("rowid")
);
CREATE TABLE IF NOT EXISTS "Collections" (
    "collection" TEXT NOT NULL,
    "folderid" INTEGER NOT NULL,
    "rowid" INTEGER NOT NULL,
    FOREIGN KEY("folderid") REFERENCES "Folders"("rowid"),
    UNIQUE("collection", "folderid"),
    PRIMARY KEY("rowid")
);
CREATE TABLE IF NOT EXISTS "Folders" (
    "rowid" INTEGER NOT NULL,
    "path" TEXT NOT NULL,
    PRIMARY KEY("rowid")
);
CREATE TABLE IF NOT EXISTS "PracticeSetups" (
    "chart_id" INTEGER NOT NULL,
    "setup_title" TEXT NOT NULL,
    "loop_success" INTEGER NOT NULL,
    "loop_fail" INTEGER NOT NULL,
    "range_begin" INTEGER NOT NULL,
    "range_end" INTEGER NOT NULL,
    "fail_cond_type" INTEGER NOT NULL,
    "fail_cond_value" INTEGER NOT NULL,
    "playback_speed" REAL NOT NULL,
    "inc_speed_on_success" INTEGER NOT NULL,
    "inc_speed" REAL NOT NULL,
    "inc_streak" INTEGER NOT NULL,
    "dec_speed_on_fail" INTEGER NOT NULL,
    "dec_speed" REAL NOT NULL,
    "min_playback_speed" REAL NOT NULL,
    "max_rewind" INTEGER NOT NULL,
    "max_rewind_measure" INTEGER NOT NULL,
    "rowid" INTEGER NOT NULL,
    FOREIGN KEY("chart_id") REFERENCES "Charts"("rowid"),
    PRIMARY KEY("rowid")
);
CREATE TABLE IF NOT EXISTS "Scores" (
    "score" INTEGER NOT NULL,
    "crit" INTEGER NOT NULL,
    "near" INTEGER NOT NULL,
    "miss" INTEGER NOT NULL,
    "gauge" REAL NOT NULL,
    "gauge_type" INTEGER NOT NULL,
    "gauge_opt" INTEGER NOT NULL,
    "auto_flags" INTEGER NOT NULL,
    "mirror" INTEGER NOT NULL,
    "random" INTEGER NOT NULL,
    "timestamp" INTEGER NOT NULL,
    "replay" TEXT NOT NULL,
    "user_name" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "local_score" INTEGER NOT NULL,
    "window_perfect" INTEGER NOT NULL,
    "window_good" INTEGER NOT NULL,
    "window_hold" INTEGER NOT NULL,
    "window_miss" INTEGER NOT NULL,
    "window_slam" INTEGER NOT NULL,
    "chart_hash" TEXT NOT NULL,
    "early" INTEGER NOT NULL,
    "late" INTEGER NOT NULL,
    "combo" INTEGER NOT NULL,
    "rowid" INTEGER NOT NULL,
    FOREIGN KEY("chart_hash") REFERENCES "Charts"("hash"),
    PRIMARY KEY("rowid")
)