[package]
name = "multiplayer-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio = { version = "1", features = ["net", "io-util"] }
anyhow = "1"
