[package]
name = "kson-effect-param-macro"
version = "0.1.1"
edition = "2021"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.18"
proc-macro2 = "1.0.37"
syn = "2.0.31"
