// This file has been generated by Specta. DO NOT EDIT.

export type SortDir = "Asc" | "Desc"

export type SongFilterType = "None" | { Folder: string } | { Collection: string }

export type GameState = { variant: "None" } | { variant: "TitleScreen" } | { variant: "SongSelect"; search_string: string; level_filter: number; folder_filter_index: number; sort_index: number; filters: SongFilterType[]; sorts: SongSort[] }

export type ClientEvent = { variant: "Invalid"; v: string } | { variant: "Start" } | { variant: "Back" } | { variant: "SetSearch"; v: string } | { variant: "SetLevelFilter"; v: number } | { variant: "SetSongFilterType"; v: SongFilterType } | { variant: "SetSongSort"; v: SongSort }

export type SongSort = { sort_type: SongSortType; direction: SortDir }

export type SongSortType = "Title" | "Score" | "Date" | "Artist" | "Effector"

