name: Android APK
on:
  push:
    branches: [android, master]
jobs:
  apk:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-${{ runner.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install llvm squashfs-tools
      - run: cargo install --git https://github.com/rust-mobile/xbuild
      - name: Build
        run: |
          . "$HOME/.cargo/env"
          x doctor
          x build -r -p rusc --arch arm64 --platform android
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: game-apk
          path: ${{ github.workspace }}/target/x/release/android/rusc.apk
